inherit: 
    - wandb.yaml

model:
    family: matrix_chain_transformer
    n_dims: 12  # 3*n (for n=4)
    n_embd: 128
    n_head: 4
    n_layer: 1  # Not used by matrix_chain_transformer
    L: 3  # Number of M_i blocks
    n: 4  # Matrix size

training:
    task: matrix_chain
    data: matrix_chain
    task_kwargs: {"L": 30, "n": 2, "m": 2, "p": 2, "q": 2}
    batch_size: 256
    learning_rate: 0.0003
    train_steps: 10000
    curriculum:
        dims:
            start: 12
            end: 12
            inc: 0
            interval: 2000
        points:
            start: 36
            end: 36
            inc: 0
            interval: 2000

out_dir: ../models/matrix_chain_custom

wandb:
    name: "matrix_chain_custom_transformer"

