inherit: 
    - base.yaml

model:
    n_dims: 4  # n+p+q (4+4+4)
    n_positions: 200  # L * (n+p+q) = 3 * 12

training:
    task: matrix_chain
    data: matrix_chain
    task_kwargs: {"L": 50, "n": 2, "m": 2, "p": 2, "q": 2}
    batch_size: 64
    learning_rate: 0.0001
    train_steps: 50000
    curriculum:
        dims:
            start: 6
            end: 6
            inc: 0
            interval: 2000
        points:
            start: 1000
            end: 1000
            inc: 0
            interval: 2000

out_dir: ../models/matrix_chain

wandb:
    name: "matrix_chain_standard"

