inherit: 
    - base.yaml

model:
    n_dims: 12  # n+p+q (4+4+4)
    n_positions: 36  # L * (n+p+q) = 3 * 12

training:
    task: matrix_chain
    data: matrix_chain
    task_kwargs: {"L": 3, "n": 4, "m": 4, "p": 4, "q": 4}
    batch_size: 64
    learning_rate: 3e-4
    train_steps: 10000
    curriculum:
        points:
            start: 12
            end: 36
            inc: 12
            interval: 2000

out_dir: ../models/matrix_chain

wandb:
    name: "matrix_chain_standard"

