inherit: 
    - base.yaml

training:
    task: table_connectivity
    task_kwargs: {"V": 5, "C": 3, "rho": 0.5}
    num_training_examples: 1024
    data: table_connectivity  # Use custom sampler for table connectivity
    batch_size: 256  # Optimized for 4 GPUs (64 per GPU)
    curriculum:
        points:
            start: 18
            end: 18
            inc: 0
            interval: 2000
        dims:
            start: 20
            end: 20
            inc: 1
            interval: 2000
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 1000
    train_steps: 5001


out_dir: ../models/table_connectivity

wandb:
    name: "table_connectivity_standard"

