inherit: 
    - base.yaml

model:
    family: lowrank_gpt2
    n_positions: 83  # V*(C+1)+3 = 20*4+3 = 83
    n_dims: 5
    n_embd: 256
    n_layer: 12
    n_head: 8
    V: 20
    C: 3

training:
    task: table_connectivity
    task_kwargs: {"V": 20, "C": 3, "rho": 0.5}
    num_training_examples: 1000000
    data: table_connectivity_fixed  # Use fixed embedding sampler
    batch_size: 256  # Optimized for 4 GPUs (64 per GPU)
    curriculum:
        points:
            start: 18
            end: 18
            inc: 0
            interval: 2000
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
    learning_rate: 0.0001
    save_every_steps: 100
    keep_every_steps: 100
    train_steps: 1001


out_dir: ../models/table_connectivity_lowrank_fixed

wandb:
    name: "table_connectivity_lowrank_fixed_embedding"



